### ISSUE TITLE
GNOME 45 compatibility

### ISSUE THREAD

**Issue by AlphaRant9** [lx358hcl/linuxiconhiderupdated#1]
Please add GNOME 45 compatibility

**Comment by lx358hcl** [comment]
@AlphaRant9 Hey, I’ll add that and reupload a new version to  the gnome extension website👍 Gimme a day

**Comment by AlphaRant9** [comment]
Awesome, thanks!

**Comment by AlphaRant9** [comment]
If you could send a link in this issue as well when it's done, that would be greatly appreciated :3

**Comment by lx358hcl** [comment]
@AlphaRant9 Hey, Gnome-45 has introduced a ton of changes which breaks everything in my extension:
https://gjs.guide/extensions/upgrading/gnome-shell-45.html

I don't have the time to port it to 45 at the currentmoment. Sorry.
If you want to have a go at it, please do, and just make a pull-request here if you want me to merge it and re-release it for 45.

**Comment by lx358hcl** [comment]
Closing it
